AllCops:
  Exclude:
    - "bin/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
